### ISSUE TITLE
environpatch.sh does not reflect current version of Environ for v1.1

### ISSUE THREAD

**Issue by jhskone** [environ-developers/Environ#1]
Super benign, but will point out as message reflected when patching caused some initial confusion. v1.1 still sets  ENVIRON_VERSION="1.0" in environpatch.sh

`git describe --tags`
 v1.1
`grep ENVIRON_VERSION Environ/patches/environpatch.sh`
export ENVIRON_VERSION="1.0"

**Comment by edan-bainglass** [comment]
Apologies for the 2+ year delay. This matter has been addressed. Thanks
