### ISSUE TITLE
Help: How to accurately optimize the adstructure with non-linear size-modified Poisson-Boltzmann implicit solvation model?

### ISSUE THREAD

**Issue by Fly330** [environ-developers/Environ#2]
Dear experts,
This is Yuan Fang. My research focuses on first principles simulation of infrared and Raman spectra of adsorbates at liquid/solid electrochemical interfaces. Recently, I plan to use non-linear size-modified Poisson-Boltzmann (MPB) equation to simulate the solvation layer of the CO/Pt(111) adsorption system. The parameters of electronic structure calculations and implicit solvation model have been listed in Fig.1. 
![Screen Shot 2021-09-12 at 11 31 14 PM](https://user-images.githubusercontent.com/21698419/132994186-ec2c022c-f576-44ca-a595-e3c73c8ec1af.png)
![Screen Shot 2021-09-12 at 11 31 27 PM](https://user-images.githubusercontent.com/21698419/132994196-beb36a61-f7b7-4287-8e22-ae2cdd5b1248.png)
Fig.1

However, the code notices that “electrolyte charge not converged” and I fail to optimize the adstructure with MPB implicit solvation model (Fig.2). 

![Screen Shot 2021-09-12 at 11 36 21 PM](https://user-images.githubusercontent.com/21698419/132994206-dbae5dcb-2341-4ff8-93fb-d6ab976741f7.png)
Fig.2

**Could you please teach me how to accurately optimize the adstructure with MPB implicit solvation model?** Many thanks!

Best Regards,
Yuan Fang

**Comment by edan-bainglass** [comment]
Apologies for the delay. Our GitHub Issues page is meant for issues relating to the code itself. For questions regarding the use of Environ, please refer to the FAQ page of our website at http://www.quantum-environ.org/faqs.html.
