### ISSUE TITLE
Asking for the methanol parameters

### ISSUE THREAD

**Issue by ghifi37** [environ-developers/Environ#4]
Hi, developers, 

Thank you for the great work to implement the solvent model in QE!
It will be much better if more solvent models are included in the software!
Do you have the methanol parameters for modeling? I only know the dielectric constant, but I need the calculation with methanol.

**Comment by matthew-truscott** [comment]
We are in fact currently working on generating parameters for methanol and other solvents! If you need this soon, we can prioritize methanol. Let me know what solvents you're interested in specifically.

**Comment by ghifi37** [comment]
Hi, Matthew! Thank you for your kind response! I just need a solvent model for methanol. You can post the parameters directly here or email me via ghifi37 at qq.com.

**Comment by ghifi37** [comment]
Dear developers, hope all of you and your development are well! 
I just wonder that is there any update about solvent models? I really hope more models are available.
